import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SessionProvider, useSession } from "next-auth/react";
import { auth } from "@/auth";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    
      <html lang="en" suppressHydrationWarning={true}>
        <SessionProvider session={session}>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            forcedTheme="dark"
            storageKey="site-theme"
          >
            <Toaster />
            {children}
          </ThemeProvider>
        </body>
        </SessionProvider>
      </html>
    
  );
}
